### ISSUE TITLE
Getters and Setters are not being generated properly.

### ISSUE THREAD

**Issue by thomasdarimont** [admiralsmaster/taxcalculator#3]
The `gettersAndSetters` and `getters` templates in the current XSLT definition don't match against the given xml format.

Expected is `/PAP/VARIABLES/INPUT` where the actual path is `/PAP/VARIABLES/INPUTS/INPUT`
same story with:
`/PAP/VARIABLES/OUTPUT` and `/PAP/VARIABLES/OUTPUTS/OUTPUT`

**Comment by admiralsmaster** [comment]
Fixed with your pull request.
Thank you very much.
