### ISSUE TITLE
Add support for dynamic lookup of Lohnsteuer Calculation Strategies.

### ISSUE THREAD

**Issue by thomasdarimont** [admiralsmaster/taxcalculator#8]
It would be nice if there was a facility for programatically looking up
Lohnsteuer calculation strategies based on some key or date parameter.

This would be helpful for applications that need to dynamically 
select the appropriate calculation strategy based on some context.

In order to support this there must be some sort of interface to abstract the actual calculation.
The interface needs to be able to deal with varying input since the calculation input and output fields
change from time to time.

I gave this a quick spin in my [feature/calculator-lookup-support](https://github.com/thomasdarimont/taxcalculator/blob/feature/calculator-lookup-support/src/test/java/info/kuechler/bmf/taxcalculator/LohnsteuerCalculatorTest.java) branch.

```java
public class LohnsteuerCalculatorTest {

    LohnsteuerCalculator calculator;

    @Before
    public void setup() {
        calculator = new DefaultLohnsteuerCalculator();
    }

    @Test
    public void testCalculateWithInputParameters() throws Exception {

        Map<String, Object> input = new HashMap<>();
        input.put("LZZ", 2); // monthly payment
        input.put("STKL", 1); // tax class
        input.put("RE4", new BigDecimal("223456")); // income in cent
        input.put("LZZFREIB", BigDecimal.ZERO); // Freibeträge
        input.put("PVS", 0); // not in saxony
        input.put("PVZ", 0); // Additional care insurance for employee: birth > 1940, older
                             // than 23, no kids
        input.put("R", 0); // no church
        input.put("ZKF", new BigDecimal("0.5")); // a half child :)
        input.put("KVZ", new BigDecimal("0.90")); // additional med insurance [percent]
        input.put("KRV", 1); // pensions fund: east germany

        input.put("VBEZ", BigDecimal.ZERO);
        input.put("LZZHINZU", BigDecimal.ZERO);
        input.put("SONSTB", BigDecimal.ZERO);
        input.put("VKAPA", BigDecimal.ZERO);
        input.put("VMT", BigDecimal.ZERO);

        CalculationOutput output = calculator.calculate("201512", input);
        
        assertThat(output.getProperty("LSTLZZ", BigDecimal.class).divide(new BigDecimal("100")),
                is(new BigDecimal("239.41")));
        assertThat(
                output.getProperty("SOLZLZZ", BigDecimal.class).divide(new BigDecimal("100")),
                is(new BigDecimal("7.79")));
        
        System.out.println(output.getProperties());
        
    }
}
``` 

Here the calculation is looked up based on a date kay pattern which internally resolves to
the appropriate LohnsteuerCalculation. The calculation input is provided as a `Map ` as well as the output but the latter is wrapped in a `CalculationOutput`.

The `DefaultLohnsteuerCalculator` provides access to the supported `LohnsteuerCalculations` that can be resolved via  a date pattern key that allow direct lookup as well as "lenient" lookups where we lookup the actual valid calculation for the particular date range a calculation is valid based on the provided key.

Some examples are show in the [LohnsteuerCalculatorFactoryTests](https://github.com/thomasdarimont/taxcalculator/blob/feature/calculator-lookup-support/src/test/java/info/kuechler/bmf/taxcalculator/LohnsteuerCalculatorFactoryTests.java).

**Comment by admiralsmaster** [comment]
I merge my solution into the main branch.
See the simple [FactoryTest.java](https://github.com/admiralsmaster/taxcalculator/blob/master/src/test/java/info/kuechler/bmf/taxcalculator/rw/FactoryTest.java) for an example.

**Comment by admiralsmaster** [comment]
see version 2016.1.1
